# Generated by Django 3.1.1 on 2020-09-29 17:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200928_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='highest_bid',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='highest_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highest_bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
